# Generated by Django 4.2.4 on 2024-05-15 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_medicinas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicinas',
            old_name='marca',
            new_name='principio_activo',
        ),
    ]
